version: '3'

services:
  inventory:
    container_name: inventory   
    build:
      context: .                
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always            
